# Site settings
course_name: Lessons of the Lawn
course_description: "The study of architecture as a speculation on the origins of ideas is located at the conjunctive core of any liberal arts curriculum and serves as the physical armature and conceptual foundation of the University. This course is concerned with the contemporary imagination, attempting to make the discipline of architecture meaningful to a wide range of citizens in its public obligation to be constructive and optimistic in the most profoundly ethical, pragmatic, and magical of terms."
course_semester: "Fall 2023"

baseurl: "/LOTL_Test" # the subpath of your site, e.g. /blog/
url: "http://fangfranksun.github.io/" # the base hostname & protocol for your site

schoolname: "UVA"
schoolurl: "https://arch.virginia.edu"
#twitter_username: username 

address: |
    School of Architecture
    University of Virginia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
